version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    # depends_on:
    #   - db
    env_file:
      - .env
    # environment:
    # DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB?schema=public
#   db:
#     build:
#       context: .
#       dockerfile: Dockerfile-db
#     restart: always
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "127.0.0.1:${DB_PORT:-5432}:5432"
#     environment:
#       POSTGRES_USER: $POSTGRES_USER
#       POSTGRES_PASSWORD: $POSTGRES_PASSWORD
#       POSTGRES_DB: $POSTGRES_DB
# volumes:
#   postgres_data:
